"""empty message

Revision ID: f29e1bfd4951
Revises: f8833062c1b6
Create Date: 2022-09-12 17:19:22.915434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f29e1bfd4951'
down_revision = 'f8833062c1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'book_picture',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'book_picture',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
